DMAN-250: Checkpoint where Helm deploy is working.

diff --git a/charts/ska-dlm/templates/postgrest.yaml b/charts/ska-dlm/templates/postgrest.yaml
--- a/charts/ska-dlm/templates/postgrest.yaml
+++ b/charts/ska-dlm/templates/postgrest.yaml
@@ -16,27 +16,28 @@ spec:
   selector:
     component: {{ .Values.postgrest.component }}
     subsystem: {{ .Values.postgrest.subsystem }}
-{{- if $.Values.postgresql.enabled }}
+{{- if .Values.postgresql.enabled }}
 ---
 apiVersion: v1
 kind: Secret
 metadata:
-  name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
-  namespace: {{ $.Release.Namespace }}
+  name: {{ include "ska-dlm.postgrest.db-auth-secret-name" . }}
+  namespace: {{ .Release.Namespace }}
   labels:
-    {{- include "ska-dlm.postgrest.labels" $ | nindent 4 }}
+    {{- include "ska-dlm.postgrest.labels" . | nindent 4 }}
 type: Opaque
 data:
-  PGHOST: {{ include "ska-dlm.postgresql.name" $ | b64enc }}
-  PGUSER: {{ $.Values.postgresql.auth.username | b64enc }}
-  PGPASSWORD: {{ $.Values.postgresql.auth.password | b64enc }}
-  PGDATABASE: {{ $.Values.postgresql.auth.database | b64enc }}
-{{- else -}}
-{{  with .Values.postgrest.db_auth_secret -}}
-{{- if .create -}}
-{{- if or (not .vault.mount) (not .vault.type) (not .vault.path) -}}
-{{- fail (printf "No embedded PostgreSQL server enabled (postgresql.enabled=%s), but Vault values are missing (postgrest.db_auth_secret.vault.{mount,type,path})" ($.Values.postgresql.enabled | toString)) -}}
-{{- end -}}
+  PGHOST: {{ include "ska-dlm.postgresql.name" . | b64enc }}
+  PGPORT: {{ "5432" | b64enc }}
+  PGUSER: {{ .Values.postgresql.auth.username | b64enc }}
+  PGPASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
+  PGDATABASE: {{ .Values.postgresql.auth.database | b64enc }}
+{{- else }}
+{{- with .Values.postgrest.db_auth_secret }}
+{{- if .create }}
+{{- if or (not .vault.mount) (not .vault.type) (not .vault.path) }}
+{{- fail (printf "No embedded PostgreSQL server enabled (postgresql.enabled=%s), but Vault values are missing (postgrest.db_auth_secret.vault.{mount,type,path})" ($.Values.postgresql.enabled | toString)) }}
+{{- end }}
 ---
 apiVersion: secrets.hashicorp.com/v1beta1
 kind: VaultStaticSecret
@@ -52,8 +53,8 @@ spec:
     name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
     transformation:
       excludeRaw: true
-{{- end -}}
-{{- end -}}
+{{- end }}
+{{- end }}
 {{- end }}
 ---
 apiVersion: apps/v1
@@ -76,61 +77,79 @@ spec:
     spec:
       {{- if .Values.postgresql.enabled }}
       initContainers:
-      - name: wait-for-postgresql
-        image: {{ .Values.kubectl.image }}:{{ .Values.kubectl.version }}
-        imagePullPolicy: {{ .Values.kubectl.imagePullPolicy }}
-        command:
-        - kubectl
-        - wait
-        - pod
-        - --for=condition=ready
-        - {{ include "ska-dlm.postgresql.name" . }}-0
-        - --timeout
-        - 120s
-      serviceAccountName: {{ $rbac_name }}
+        - name: wait-for-postgresql
+          image: postgres:17
+          command: ["/bin/sh", "-c"]
+          args:
+            - |
+              MAX_RETRIES=40
+              RETRY_COUNT=0
+              DELAY=3
+
+              until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
+                pg_isready -h {{ include "ska-dlm.postgresql.name" . }} -p 5432 && exit 0
+                RETRY_COUNT=$((RETRY_COUNT + 1))
+                echo "Attempt $RETRY_COUNT failed. Retrying in $DELAY seconds..."
+                sleep $DELAY
+              done
+              echo "PostgreSQL not ready"
+              exit 1
+
+        - name: wait-for-dlm-schema
+          image: postgres:17-bookworm
+          command: ["/bin/sh", "-c"]
+          args:
+            - |
+              until psql -h {{ include "ska-dlm.postgresql.name" . }} \
+                        -U {{ .Values.postgresql.auth.username }} \
+                        -d {{ .Values.postgresql.auth.database }} \
+                        -tAc "SELECT 1 FROM pg_namespace WHERE nspname = 'dlm'" | grep -q 1; do
+                echo "Waiting for dlm schema..."
+                sleep 3
+              done
+          env:
+            - name: PGPASSWORD
+              value: {{ .Values.postgresql.auth.password | quote }}
       {{- end }}
       containers:
-      - name: postgrest
-        image: {{ .Values.postgrest.image}}:{{ .Values.postgrest.version }}
-        imagePullPolicy: {{ .Values.postgrest.imagePullPolicy }}
-        readinessProbe:
-          httpGet:
-            path: /
-            port: 3001
-          initialDelaySeconds: 5
-          periodSeconds: 5
-        env:
-          {{/* DB connection parameters are first read from the secret, then put into PGRST_DB_URI */ -}}
-          {{ range $envvar_name := tuple "PGUSER" "PGPASSWORD" "PGHOST" "PGDATABASE" -}}
-          - name: {{ $envvar_name }}
-            valueFrom:
-              secretKeyRef:
-                name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
-                key: {{ $envvar_name }}
-                optional: false
-          {{ end -}}
-          - name: PGRST_DB_URI
-            value: "postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST)/$(PGDATABASE)"
-
-          {{- /* The rest of the configuration is always taken from the given Helm values */ -}}
-          {{ $env := dict
-            "PGRST_SERVER_PORT" 3001
-            "PGRST_DB_ANON_ROLE" .Values.postgrest.db_anon_role
-            "PGRST_DB_POOL" .Values.postgresql.db_pool
-            "PGRST_SERVER_HOST" .Values.postgrest.server_host
-            "PGRST_SECRET_IS_BASE64" .Values.postgrest.secret_is_base64
-            "PGRST_MAX_ROWS" .Values.postgrest.max_rows
-            "PGRST_PRE_REQUEST" .Values.postgrest.pre_request
-            "PGRST_ROLE_CLAIM_KEY" .Values.postgrest.role_claim_key
-            "PGRST_DB_SCHEMA" .Values.postgrest.db_schema
-            "PGRST_LOG_LEVEL" .Values.postgrest.log_level
-          }}
-          {{- range $envvar_name, $value := $env }}
-          {{- if $value }}
-          - name: {{ $envvar_name }}
-            value: {{ $value | quote }}
-          {{- end }}
-          {{- end }}
+        - name: postgrest
+          image: {{ .Values.postgrest.image }}:{{ .Values.postgrest.version }}
+          imagePullPolicy: {{ .Values.postgrest.imagePullPolicy }}
+          readinessProbe:
+            httpGet:
+              path: /
+              port: 3001
+            initialDelaySeconds: 5
+            periodSeconds: 5
+          env:
+            {{- range $envvar_name := tuple "PGUSER" "PGPASSWORD" "PGHOST" "PGPORT" "PGDATABASE" }}
+            - name: {{ $envvar_name }}
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
+                  key: {{ $envvar_name }}
+                  optional: false
+            {{- end }}
+            - name: PGRST_DB_URI
+              value: "postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST):$(PGPORT)/$(PGDATABASE)"
+            {{- $env := dict
+              "PGRST_SERVER_PORT" "3001"
+              "PGRST_DB_ANON_ROLE" .Values.postgrest.db_anon_role
+              "PGRST_DB_POOL" .Values.postgrest.db_pool
+              "PGRST_SERVER_HOST" .Values.postgrest.server_host
+              "PGRST_SECRET_IS_BASE64" .Values.postgrest.secret_is_base64
+              "PGRST_MAX_ROWS" .Values.postgrest.max_rows
+              "PGRST_PRE_REQUEST" .Values.postgrest.pre_request
+              "PGRST_ROLE_CLAIM_KEY" .Values.postgrest.role_claim_key
+              "PGRST_DB_SCHEMA" .Values.postgrest.db_schema
+              "PGRST_LOG_LEVEL" .Values.postgrest.log_level
+            }}
+            {{- range $envvar_name, $value := $env }}
+            {{- if $value }}
+            - name: {{ $envvar_name }}
+              value: {{ $value | quote }}
+            {{- end }}
+            {{- end }}
 {{- if .Values.postgresql.enabled }}
 ---
 apiVersion: v1
@@ -145,9 +164,9 @@ metadata:
   name: {{ $rbac_name }}
   namespace: {{ .Release.Namespace }}
 subjects:
-- kind: ServiceAccount
-  name: {{ $rbac_name }}
-  namespace: {{ .Release.Namespace }}
+  - kind: ServiceAccount
+    name: {{ $rbac_name }}
+    namespace: {{ .Release.Namespace }}
 roleRef:
   kind: Role
   name: {{ $rbac_name }}
@@ -159,7 +178,7 @@ metadata:
   name: {{ $rbac_name }}
   namespace: {{ .Release.Namespace }}
 rules:
-- apiGroups: [""]
-  resources: ["pods"]
-  verbs: ["get", "list", "watch"]
+  - apiGroups: [""]
+    resources: ["pods"]
+    verbs: ["get", "list", "watch"]
 {{- end }}
