DMAN-167: Add location config to charts

diff --git a/charts/ska-dlm/templates/storage.yaml b/charts/ska-dlm/templates/storage.yaml
--- a/charts/ska-dlm/templates/storage.yaml
+++ b/charts/ska-dlm/templates/storage.yaml
@@ -34,6 +34,24 @@ spec:
       labels:
         {{- include "ska-dlm.storage.labels" . | indent 8 }}
     spec:
+      initContainers:
+        - name: wait-for-pod
+          image: curlimages/curl
+          command: ["/bin/sh", "-c"]
+          args:
+            - |
+              MAX_RETRIES=40
+              RETRY_COUNT=0
+              DELAY=3
+
+              until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
+                curl --fail http://{{ include "ska-dlm.fullname" . }}-postgrest/data_item && exit 0
+                RETRY_COUNT=$((RETRY_COUNT + 1))
+                echo "Attempt $RETRY_COUNT of $MAX_RETRIES failed. Retrying in $DELAY seconds..."
+                sleep $DELAY
+              done
+              echo "Failed after $MAX_RETRIES attempts."
+              exit 1
       containers:
       - name: storage
         image: {{ .Values.storage.image}}:{{ .Values.storage.version }}
@@ -46,8 +64,10 @@ spec:
         - --port
         - "8003"
         env:
-          - name: CONFIG
+          - name: STORAGE_CONFIG
             value: "/etc/storage-config.json"
+          - name: LOCATION_CONFIG
+            value: "/etc/location-config.json"
         ports:
         - containerPort: 8003
           name: http-port
@@ -69,6 +89,10 @@ spec:
           mountPath: "/etc/storage-config.json"
           subPath: storage-config.json
           readOnly: true
+        - name: location-configmap
+          mountPath: "/etc/location-config.json"
+          subPath: location-config.json
+          readOnly: true
       volumes:
       - name: dlm-configmap
         configMap:
@@ -76,3 +100,6 @@ spec:
       - name: storage-configmap
         configMap:
           name: {{ include "ska-dlm.fullname" . }}-storage-configmap
+      - name: location-configmap
+        configMap:
+          name: {{ include "ska-dlm.fullname" . }}-location-configmap
